# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "apim-helm-gw.resource.prefix" . }}-shared-synapse-configs
  namespace : {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistence.sharedArtifacts.capacity.synapseConfigs }}
  selector:
    matchLabels:
      purpose: synapse-configs
  storageClassName: {{ template "apim-helm-gw.resource.prefix" . }}-sc
