# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# --------------------------------------------------------------------------------------

{{- if and .Values.kubernetes.gatewayAPI.enabled .Values.kubernetes.gatewayAPI.websub.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "apim-helm-gw.fullname" . }}-websub-httproute
  namespace: {{ .Release.Namespace }}
{{- if .Values.kubernetes.gatewayAPI.websub.annotations }}
  annotations:
{{ toYaml .Values.kubernetes.gatewayAPI.websub.annotations | indent 4 }}
{{- end }}
spec:
  parentRefs:
  - name: {{ .Values.kubernetes.gatewayAPI.gatewayName }}
    sectionName: websub-https
  hostnames:
  - {{ .Values.kubernetes.gatewayAPI.websub.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ template "apim-helm-gw.fullname" . }}-service
      port: {{ add 8021 (.Values.wso2.apim.portOffset | default 0) }}
    {{- if .Values.kubernetes.gatewayAPI.websub.filters }}
    filters:
{{ toYaml .Values.kubernetes.gatewayAPI.websub.filters | indent 4 }}
    {{- end }}
{{- end }}
